repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: no-commit-to-branch
        args: [ --branch, master ]
      - id: pretty-format-json
        args: [ --autofix, --no-sort-keys ]
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        args: [ --end-of-line, lf, ReleaseNotes.md, README.md ]
        additional_dependencies:
          - mdformat-gfm
          - mdformat_frontmatter

  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.3.0
  #   hooks:
  #     - id: codespell
  #       args: [ --write, --toml, pyproject.toml ]
  #       additional_dependencies:
  #         - tomli

  # - repo: https://github.com/psf/black
  #   rev: 24.8.0
  #   hooks:
  #     - id: black
  #       language_version: python3

  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.1.1
  #   hooks:
  #   - id: flake8
  #     language_version: python3
  #     exclude: 'templates'
