name: Build-and-Deploy-to-Production

on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write

    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.12' ]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git identity
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Merge into master
        id: merge_into_master
        run: |
          git checkout master
          git merge --no-ff $GITHUB_REF
        continue-on-error: false

      - name: Push to master
        if: steps.merge_into_master.outcome == 'success'
        run: |
          git push origin master

      - name: Create zip of PowerShell and config files
        run: |
          zip ./Installation-Files.zip ./README.md ./LICENSE ./ReleaseNotes.md ./Manifest.psd1
          cd src
          zip ../Installation-Files.zip *.ps1

      - name: New release
        uses: softprops/action-gh-release@v2
        with:
          # tag_name: ${{ vars.GITHUB_HEAD_REF }}
          # name: ${{ vars.GITHUB_HEAD_REF }}
          body_path: ${{ github.workspace }}/ReleaseNotes.md
          draft: false
          prerelease: false
          files: |
            Installation-Files.zip
            ./src/Conclude-Install.ps1
            ./Manifest.psd1

      - name: Send release email notification
        uses: betterfor/action-send-mail@main
        with:
          server_address: mail.realtimeevents.co
          server_port: 465
          username: ${{ vars.GMAIL_USER }}
          password: ${{ vars.GMAIL_APP_PASSWORD }}
          subject: 'New Release: ${{ github.repository }} ${{ github.ref_name }}'
          to: rte-development@brightedge.co.za
          from: Development Messenger
          html_body: |
            <table style="font-family: verdana;font-size:90%; border-collapse:collapse; border-style: double; border-color: 000000; border-width: 3px">
              <colgroup>
                <col style="text-align:right">
                <col style="text-align:left">
              </colgroup>
              <tr>
                <th style="text-align: center; border-bottom-style: double; border-right-style: double; border-right-width: 1px; border-bottom-width: 3px">Description</th>
                <th style="text-align: center; border-bottom-style: double; border-left-style: double; border-bottom-width: 3px; border-left-width: 1px">Detail</th>
              </tr>
              <tr>
                <td style="text-align: right; border-right-style: solid; border-bottom-style: dotted; border-right-width: 1px;border-bottom-width: 1px">Repository:</td>
                <td style="text-align: left; border-bottom-style: dotted; border-left-style: solid; border-left-width: 1px;border-bottom-width: 1px">${{ github.repository }}</td>
              </tr>
              <tr>
                <td style="text-align: right; border-right-style: solid; border-bottom-style: dotted; border-right-width: 1px;border-bottom-width: 1px">Release:</td>
                <td style="text-align: left; border-bottom-style: dotted; border-left-style: solid; border-left-width: 1px;border-bottom-width: 1px">${{ github.ref_name }}</td>
              </tr>
              <tr>
                <td style="text-align: right; border-right-style: solid; border-bottom-style: dotted; border-right-width: 1px;border-bottom-width: 1px">Actor:</td>
                <td style="text-align: left; border-bottom-style: dotted; border-left-style: solid; border-left-width: 1px;border-bottom-width: 1px">${{ github.actor }}</td>
              </tr>
              <tr>
                <td style="text-align: right; border-right-style: solid; border-bottom-style: dotted; border-right-width: 1px;border-bottom-width: 1px">Workflow:</td>
                <td style="text-align: left; border-bottom-style: dotted; border-left-style: solid; border-left-width: 1px;border-bottom-width: 1px">${{ github.workflow }}</td>
              </tr>
              <tr>
                <td style="text-align: right; border-right-style: solid; border-right-width: 1px">Release URL:</td>
                <td style="text-align: left; border-left-style: solid; border-left-width: 1px"><a href="https://github.com/${{ github.repository }}/releases/tag/${{github.ref_name}}">Click here</a></td>
              </tr>
            </table><br>
          priority: normal
